# Generated by Django 5.2.1 on 2025-06-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
    ]
